version: '3.8'

services:
  mobsf:
    image: opensecurity/mobile-security-framework-mobsf:latest
    container_name: mobsf-dev
    ports:
      - "8000:8000"
    environment:
      - MOBSF_API_ONLY=1
    volumes:
      - mobsf_dev_data:/home/mobsf/.MobSF
      - ./test_apks:/home/mobsf/test_apks:ro  # Mount test APKs
    networks:
      - security_dev_net
    restart: unless-stopped

  security-agent:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: security-agent-dev
    ports:
      - "8080:8000"
    environment:
      - MOBSF_URL=http://mobsf:8000
      - MOBSF_API_KEY=${MOBSF_API_KEY:-your-mobsf-api-key}
      - GROQ_API_KEY=${GROQ_API_KEY:-your-groq-api-key}
      - AI_PROVIDER=groq
      - AI_MODEL=llama-3.3-70b-versatile
      - DEBUG=true
      - PYTHONPATH=/app
    volumes:
      - .:/app:ro  # Mount source code for development
      - agent_dev_outputs:/app/outputs
      - agent_dev_reports:/app/reports
      - agent_dev_scans:/app/scans
    networks:
      - security_dev_net
    depends_on:
      - mobsf
    restart: unless-stopped
    # Override command for development
    command: ["python", "-u", "enhanced_api_server.py"]

networks:
  security_dev_net:
    driver: bridge

volumes:
  mobsf_dev_data:
  agent_dev_outputs:
  agent_dev_reports:
  agent_dev_scans: