apiVersion: apps/v1
kind: Deployment
metadata:
  name: mobsf-deployment
  namespace: mobile-security
  labels:
    app: mobsf
    component: scanner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mobsf
  template:
    metadata:
      labels:
        app: mobsf
        component: scanner
    spec:
      containers:
      - name: mobsf
        image: opensecurity/mobile-security-framework-mobsf:latest
        ports:
        - containerPort: 8000
          name: http
        env:
        - name: MOBSF_API_ONLY
          valueFrom:
            configMapKeyRef:
              name: mobile-security-config
              key: MOBSF_API_ONLY
        volumeMounts:
        - name: mobsf-data
          mountPath: /home/mobsf/.MobSF
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /api_docs
            port: 8000
          initialDelaySeconds: 120
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /api_docs
            port: 8000
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
      volumes:
      - name: mobsf-data
        persistentVolumeClaim:
          claimName: mobsf-data-pvc
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: mobsf-service
  namespace: mobile-security
  labels:
    app: mobsf
    component: scanner
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: mobsf