apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mobsf-data-pvc
  namespace: mobile-security
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard  # Use 'hostpath' for Minikube
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: agent-outputs-pvc
  namespace: mobile-security
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: standard  # Use 'hostpath' for Minikube
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: agent-reports-pvc
  namespace: mobile-security
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard  # Use 'hostpath' for Minikube