apiVersion: apps/v1
kind: Deployment
metadata:
  name: security-agent-deployment
  namespace: mobile-security
  labels:
    app: security-agent
    component: analyzer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: security-agent
  template:
    metadata:
      labels:
        app: security-agent
        component: analyzer
    spec:
      containers:
      - name: security-agent
        image: mobile-security-agent:latest
        imagePullPolicy: Never  # For local Minikube development
        ports:
        - containerPort: 8000
          name: http
        env:
        - name: MOBSF_URL
          valueFrom:
            configMapKeyRef:
              name: mobile-security-config
              key: MOBSF_URL
        - name: MOBSF_API_KEY
          valueFrom:
            secretKeyRef:
              name: mobile-security-secrets
              key: mobsf-api-key
              optional: true
        - name: GROQ_API_KEY
          valueFrom:
            secretKeyRef:
              name: mobile-security-secrets
              key: groq-api-key
        - name: AI_PROVIDER
          valueFrom:
            configMapKeyRef:
              name: mobile-security-config
              key: AI_PROVIDER
        - name: AI_MODEL
          valueFrom:
            configMapKeyRef:
              name: mobile-security-config
              key: AI_MODEL
        - name: DEBUG
          valueFrom:
            configMapKeyRef:
              name: mobile-security-config
              key: DEBUG
        - name: HOST
          valueFrom:
            configMapKeyRef:
              name: mobile-security-config
              key: HOST
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: mobile-security-config
              key: PORT
        - name: PYTHONPATH
          valueFrom:
            configMapKeyRef:
              name: mobile-security-config
              key: PYTHONPATH
        - name: PYTHONDONTWRITEBYTECODE
          valueFrom:
            configMapKeyRef:
              name: mobile-security-config
              key: PYTHONDONTWRITEBYTECODE
        - name: PYTHONUNBUFFERED
          valueFrom:
            configMapKeyRef:
              name: mobile-security-config
              key: PYTHONUNBUFFERED
        volumeMounts:
        - name: agent-outputs
          mountPath: /app/outputs
        - name: agent-reports
          mountPath: /app/reports
        - name: agent-scans
          mountPath: /app/scans
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
      volumes:
      - name: agent-outputs
        persistentVolumeClaim:
          claimName: agent-outputs-pvc
      - name: agent-reports
        persistentVolumeClaim:
          claimName: agent-reports-pvc
      - name: agent-scans
        emptyDir: {}  # Temporary storage for scan files
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: security-agent-service
  namespace: mobile-security
  labels:
    app: security-agent
    component: analyzer
spec:
  type: LoadBalancer  # Use NodePort for Minikube
  ports:
  - port: 8080
    targetPort: 8000
    protocol: TCP
    name: http
    nodePort: 30080  # For NodePort access in Minikube
  selector:
    app: security-agent